### PR TITLE
Support "bundle" in addition to "bundlePath"

### PR DESCRIPTION
**Pull request by giuseppe**
It was changed in the OCI runtime spec to 1.0.0.rc5

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
If we change this, will it break on Docker which uses older versions of runc?

**Comment by pschiffe** [comment]
Without this PR I'm getting error:
```
oci-register-machine[1738]: 2017/09/13 11:43:13 RegisterMachine Failed to read /config.json open /config.json: no such file or directory
```

With the PR, `oci-register-machine` is working correctly for me. I'm using RHEL AH 7.4.1 with `runc-1.0.0-12.1.gitf8ce01d.el7.x86_64`

**Comment by giuseppe** [comment]
@rhatdan yes, true.  I've pushed a new version that supports both variants.

**Comment by pschiffe** [comment]
I can confirm that updated PR still works for me.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
I have pushed updated versions of oci-register-machine into fedora updates testing. Please test and give good karma.

**Comment by pschiffe** [comment]
Awesome thanks. We also need updated rpm in RHEL Atomic Host - I've created bz here: https://bugzilla.redhat.com/show_bug.cgi?id=1491461

**Comment by rhatdan** [comment]
Yup, I asked @lsm5 to make this available in 7.4.2 release.

**Pull request merged**
