### PR TITLE
Support container uuid

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@pschiffe @rhatdan @mrunalp this is the related change to get the OCI machine registered.

The config.json for the gce system container that @pschiffe is working on looks like:

```
...
    "hooks": {
        "prestart": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            },
            {
                "path": "/usr/libexec/oci/hooks.d/oci-register-machine"
            }
        ],
        "poststop": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            },
            {
                "path": "/usr/libexec/oci/hooks.d/oci-register-machine"
            }
        ]
    },
...
```

The issue is that I get a SELinux error when I try to access the journalctl though:

```
Dec 08 17:55:18 helium audit[1158]: AVC avc:  denied  { read } for  pid=1158 comm="dbus-daemon" path="/" dev="dm-1" ino=1179705 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_share_t:s0 tclass=dir permissive=0
Dec 08 17:55:21 helium setroubleshoot[32567]: SELinux is preventing dbus-daemon from read access on the directory /. For complete SELinux messages. run sealert -l ceb31e60-2e02-4f8f-800c-52fc59254018

# sealert -l ceb31e60-2e02-4f8f-800c-52fc59254018

Additional Information:
Source Context                system_u:system_r:system_dbusd_t:s0-s0:c0.c1023
Target Context                system_u:object_r:container_share_t:s0
Target Objects                / [ dir ]
Source                        dbus-daemon
Source Path                   dbus-daemon
Port                          <Unknown>
Host                          helium
Source RPM Packages           
Target RPM Packages           filesystem-3.2-37.fc24.x86_64
Policy RPM                    selinux-policy-3.13.1-224.fc25.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     helium
Platform                      Linux helium 4.8.11-300.fc25.x86_64 #1 SMP Mon Nov
                              28 18:24:51 UTC 2016 x86_64 x86_64
Alert Count                   9
First Seen                    2016-12-08 16:34:38 CET
Last Seen                     2016-12-08 17:55:18 CET
Local ID                      ceb31e60-2e02-4f8f-800c-52fc59254018

Raw Audit Messages
type=AVC msg=audit(1481216118.519:1367): avc:  denied  { read } for  pid=1158 comm="dbus-daemon" path="/" dev="dm-1" ino=1179705 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_share_t:s0 tclass=dir permissive=0


Hash: dbus-daemon,system_dbusd_t,container_share_t,dir,read

```

this issue doesn't seem related to my change.  Temporarily disabling SElinux, I am able to do:

```
# journalctl -M gce | head
-- Logs begin at Thu 2016-12-08 16:34:20 CET, end at Thu 2016-12-08 17:54:27 CET. --
Dec 08 16:34:20 localhost.localdomain systemd-journal[18]: Runtime journal is using 4.0M (max allowed 8.0M, trying to leave 9.6M free of 59.9M available → current limit 8.0M).
Dec 08 16:34:20 localhost.localdomain systemd-journal[18]: Permanent journal is using 8.0M (max allowed 4.0G, trying to leave 4.0G free of 132.3G available → current limit 4.0G).
Dec 08 16:34:20 localhost.localdomain systemd-journal[18]: Time spent on flushing to /var is 578us for 2 entries.
Dec 08 16:34:20 localhost.localdomain systemd-journal[18]: Journal started
Dec 08 16:34:20 localhost.localdomain systemd[1]: Starting Flush Journal to Persistent Storage...
```

**Comment by rhatdan** [comment]
Are you running with an Overlay backend?

**Comment by rhatdan** [comment]
https://github.com/fedora-selinux/selinux-policy/pull/175

**Comment by giuseppe** [comment]
I see this when running a runc container from /var/lib/containers/atomic

**Comment by rhatdan** [comment]
Ok makes sense.  We label those as container_share_t.

**Comment by giuseppe** [comment]
with your patch for the selinux policy, this works as expected.

**Comment by rhatdan** [comment]
Did you make sure it still works with docker?

**Comment by giuseppe** [comment]
yes, I've tested that.  If I run also a docker container, I have this:

```
# machinectl
MACHINE                          CLASS     SERVICE
8ff130c8cad5f4577a5ca045d94f3d52 container docker 
gce                              container runc   
```

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
